// src/components/Navbar.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useThemeStore } from '../stores/theme'
import { resumeData } from '../data/resume'

const themeStore = useThemeStore()
const isScrolled = ref(false)
const isMobileMenuOpen = ref(false)
const activeSection = ref('home')

const sections = computed(() => resumeData.navLinks)

function onScroll() {
  isScrolled.value = window.scrollY > 50
  updateActiveLink()
}

function updateActiveLink() {
  let current = ''
  const sectionElements = document.querySelectorAll('section[id]')
  sectionElements.forEach((section) => {
    const sectionTop = (section as HTMLElement).offsetTop - 100
    if (window.scrollY >= sectionTop) {
      current = section.getAttribute('id') || ''
    }
  })
  activeSection.value = current
}

function toggleMobileMenu() {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
  document.body.style.overflow = isMobileMenuOpen.value ? 'hidden' : ''
}

function closeMobileMenu() {
  isMobileMenuOpen.value = false
  document.body.style.overflow = ''
}

function handleDownload() {
  window.print()
}

onMounted(() => {
  window.addEventListener('scroll', onScroll, { passive: true })
  onScroll()
})

onUnmounted(() => {
  window.removeEventListener('scroll', onScroll)
})
</script>

<template>
  <nav id="navbar" :class="{ scrolled: isScrolled }">
    <div class="nav-brand">
      <span class="brand-bracket">{</span>
      <span class="brand-name">ZJ</span>
      <span class="brand-bracket">}</span>
    </div>
    <ul class="nav-links">
      <li v-for="link in sections" :key="link.href">
        <a
          :href="link.href"
          :class="{ active: activeSection === link.href.replace('#', '') }"
          @click="closeMobileMenu"
        >
          {{ link.label }}
        </a>
      </li>
    </ul>
    <div class="nav-actions">
      <button class="theme-toggle" aria-label="切换主题" @click="themeStore.toggleTheme">
        <i class="fas fa-moon"></i>
        <i class="fas fa-sun"></i>
      </button>
      <button class="btn-download" aria-label="下载简历" @click="handleDownload">
        <i class="fas fa-download"></i>
      </button>
      <button
        class="nav-toggle"
        :class="{ active: isMobileMenuOpen }"
        aria-label="Toggle menu"
        @click="toggleMobileMenu"
      >
        <span></span><span></span><span></span>
      </button>
    </div>
  </nav>
  <div class="mobile-menu" :class="{ active: isMobileMenuOpen }">
    <ul>
      <li v-for="link in sections" :key="link.href">
        <a :href="link.href" @click="closeMobileMenu">{{ link.label }}</a>
      </li>
    </ul>
  </div>
</template>

// src/components/Navbar.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useThemeStore } from '../store/theme';
import { useScrollPosition } from '../hooks/useScrollPosition';
import { resumeData } from '../data/resume';

const navItems = [
  { href: '#home', label: '首页' },
  { href: '#about', label: '关于' },
  { href: '#skills', label: '技能' },
  { href: '#experience', label: '经历' },
  { href: '#projects', label: '项目' },
  { href: '#contact', label: '联系' },
];

export default function Navbar() {
  const { theme, toggleTheme } = useThemeStore();
  const scrollY = useScrollPosition();
  const [activeSection, setActiveSection] = useState('home');
  const [mobileOpen, setMobileOpen] = useState(false);
  const sectionsRef = useRef<HTMLElement[]>([]);

  useEffect(() => {
    sectionsRef.current = Array.from(
      document.querySelectorAll('section[id]')
    ) as HTMLElement[];
  }, []);

  useEffect(() => {
    let current = '';
    sectionsRef.current.forEach((section) => {
      const sectionTop = section.offsetTop - 100;
      if (scrollY >= sectionTop) {
        current = section.getAttribute('id') || '';
      }
    });
    if (current) setActiveSection(current);
  }, [scrollY]);

  const handleNavClick = useCallback(() => {
    setMobileOpen(false);
    document.body.style.overflow = '';
  }, []);

  const toggleMobile = useCallback(() => {
    setMobileOpen((prev) => {
      const next = !prev;
      document.body.style.overflow = next ? 'hidden' : '';
      return next;
    });
  }, []);

  const handleDownload = useCallback(() => {
    window.print();
  }, []);

  const isScrolled = scrollY > 50;

  return (
    <>
      <nav id="navbar" className={isScrolled ? 'scrolled' : ''}>
        <div className="nav-brand">
          <span className="brand-bracket">{'{'}</span>
          <span className="brand-name">ZJ</span>
          <span className="brand-bracket">{'}'}</span>
        </div>
        <ul className="nav-links">
          {navItems.map((item) => (
            <li key={item.href}>
              <a
                href={item.href}
                className={activeSection === item.href.slice(1) ? 'active' : ''}
                onClick={handleNavClick}
              >
                {item.label}
              </a>
            </li>
          ))}
        </ul>
        <div className="nav-actions">
          <button
            className="theme-toggle"
            onClick={toggleTheme}
            aria-label="切换主题"
          >
            <i className="fas fa-moon" />
            <i className="fas fa-sun" />
          </button>
          <button
            className="btn-download"
            onClick={handleDownload}
            aria-label="下载简历"
          >
            <i className="fas fa-download" />
          </button>
          <button
            className={`nav-toggle${mobileOpen ? ' active' : ''}`}
            onClick={toggleMobile}
            aria-label="Toggle menu"
          >
            <span />
            <span />
            <span />
          </button>
        </div>
      </nav>

      <div className={`mobile-menu${mobileOpen ? ' active' : ''}`}>
        <ul>
          {navItems.map((item) => (
            <li key={item.href}>
              <a href={item.href} onClick={handleNavClick}>
                {item.label}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
